repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-added-large-files
        exclude: partsapp\/static\/highcharts\/highcharts\.src\.js$
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: migrations\/[^/]*\.py$|settings\/[^/]*\.py|highcharts\/$|docs\/conf\.py
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: forbid-crlf
        exclude: \.csv$|\.png$|\.bat$
    -   id: forbid-tabs
        exclude: Makefile|\.bat|highcharts\/|highcharts\/modules\/$|\.png
-   repo: git://github.com/adambrenecki/pre-commit-python-sorter
    rev: 1.0.5
    hooks:
    -   id: python-import-sorter
        exclude: migrations\/[^/]*\.py$|docs\/conf\.py
-   repo: https://github.com/prettier/prettier
    rev: 1.14.2
    hooks:
    -   id: prettier
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      language_version: python3.7
